version: "3.7"
services:
  source_db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jamesbond
      POSTGRES_PASSWORD: jamesbond
      POSTGRES_DB: postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  target_db:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: jamesbond
      POSTGRES_PASSWORD: jamesbond
      POSTGRES_DB: postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
